### ISSUE TITLE
Update UI  Docs

### ISSUE THREAD

**Issue by noque-lind** [appupgrade-dev/app-upgrade-react-native-sdk#6]
Hello, everytime i want to create an upgrade i get confused about which version to enter. Can you please make it more clear, that the version you create is the one that you want to upgrade? 

It seems like you got confused yourself when creating the documentation, because in the text you say to write 1.0.0 if you want to upgrade users to 1.0.1, however in the screenshot you have created the version as 1.0.1

![Skærmbillede 2023-10-10 kl  17 46 26](https://github.com/appupgrade-dev/app-upgrade-react-native-sdk/assets/58248091/62ea8ac8-caaa-44c6-a6da-5d9c00a139b5)

**Comment by appupgrade-dev** [comment]
@noque-lind Thanks for your feedback we will get it corrected.

**Comment by appupgrade-dev** [comment]
@noque-lind We have fixed the docs.
